### ISSUE TITLE
High-fi Feedback-Item

### ISSUE THREAD

**Issue by Mehul-Bisht** [oppia/oppia-android#2646]
High-fi Content-Item fixes for below-mentioned cases:

- Exploration View Mobile Portrait

- Exploration Split View Mobile Portrait
 
- Exploration View Tablet Portrait

- Exploration Split View Tablet Portrait
 
- Exploration View Mobile Landscape
 
- Exploration Split View Mobile Landscape
 
- Exploration View Tablet Landscape
 
- Exploration Split View Tablet Landscape
 
- Question View Mobile Portrait
 
- Question Split View Mobile Portrait
 
- Question View Tablet Portrait
 
- Question Split View Tablet Portrait
 
- Question View Mobile Landscape
 
- Question Split View Mobile Landscape
 
- Question View Tablet Landscape
 
- Question Split View Tablet Landscape

**Comment by Mehul-Bisht** [comment]
@rt4914 I think this issue should be completely solved now, may I close this issue?

**Comment by rt4914** [comment]
@Mehul-Bisht Actually this is not solved. `High-Fi` means that final UI is pixel perfect. So therefore we will need to check these values in previous PR with the correct mocks. P.S.: https://github.com/oppia/oppia-android/pull/2647#pullrequestreview-585237387
