### ISSUE TITLE
Dark theme make colors of the images distorted

### ISSUE THREAD

**Issue by prayutsu** [oppia/oppia-android#3122]
We currently do not support a dark theme but when a device enforces a dark theme on the app, then the colors of some images get distorted - 
![Screenshot_2021-04-27-11-24-27-407_org oppia android](https://user-images.githubusercontent.com/54636525/116195713-34ccee80-a750-11eb-881c-1f290cfb845c.jpg)

**Comment by BenHenning** [comment]
Note that this was found while testing alpha MR2 but is determined to not be a blocker.

**Comment by MohitGupta121** [comment]
@BenHenning @rt4914 I think this issue is now fixed as now Dark Mode is implemented in our app and in Home Screen.

I build and test from develop and I not to getting this issue:-

https://user-images.githubusercontent.com/76530270/205122164-ed9c913e-431f-4b8d-b470-ebf686d0de53.png

**Comment by BenHenning** [comment]
From a discussion in CLaM meeting, it seems like this still happening on real devices for both Mohit and Adhiambo (but not emulator). I'm wondering if this is an OEM-specific setting wherein the device is forcing dark mode image inversion.

Edit: from talking further, it seems that on Mohit's device setting the device-wide setting causes inversion but setting a per-app dark mode doesn't. I think this is due to essentially two versions of dark mode being implemented in Android whereby OEMs would force dark mode by sometimes inverting images (when normal AOSP Android only ever provided normal dark mode).

**Comment by BenHenning** [comment]
For potential solutions, might https://stackoverflow.com/a/69568872 work?
