### ISSUE TITLE
Admin Controls icon color incorrect in API 19

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#3722]
<img src="https://user-images.githubusercontent.com/9396084/130654931-3f542b98-addc-49f2-be66-fc27814509f6.png" width="250" />

In the screenshot we can notice that the icon color of `Administrator Controls` is orange even when its not selected. This needs to be fixed.

Expected behaviour:
Icon + Text color when selected -> Orange
Icon + Text color when not selected -> black

Take exact color code from colors.xml file and from other similar icons.

**Comment by aadityaguptaa** [comment]
Hey, I think the expected API level is 21+ right?

**Comment by rt4914** [comment]
> Hey, I think the expected API level is 21+ right?

@aadityaguptaa Actually for the minimum API version is 19.

**Comment by aadityaguptaa** [comment]
Ohh okay, my bad. But the project uses OkHttp which works on API 21+. That's why my app keeps crashing.

**Comment by rt4914** [comment]
> Ohh okay, my bad. But the project uses OkHttp which works on API 21+. That's why my app keeps crashing.

@aadityaguptaa Yes that's correct. I think I will have to solve this as there is one branch of mine in which I am not facing these crashes so I can leverage that to showcase that my solution works. @aadityaguptaa Can you pick some other issue to work on ?

**Comment by aadityaguptaa** [comment]
sure

**Comment by Rishavgupta12345** [comment]
please assign me this issue @rt4914 @bkaur-bkj

**Comment by bkaur-bkj** [comment]
@Rishavgupta12345 Done

**Comment by Rishavgupta12345** [comment]
can someone tell me on which file I can find this issue @rt4914

**Comment by BenHenning** [comment]
@Rishavgupta12345 this is something that you'll need to investigate. One thing that can be really helpful is to look at strings on the screen that you're trying to find the code for, then look up those strings in code (which will correspond to string IDs), and then find which layouts/Kotlin files those strings are referenced in (which will either provide the exact files responsible for that screen, or the files responsible for a constituent piece of the screen).

**Comment by rt4914** [comment]
This issue is specific to API 19 only. So please create an emulator accordingly.

**Comment by bkaur-bkj** [comment]
@Rishavgupta12345 I have unassigned this issue as per your request, do let me know in case you want to pick it up again

**Comment by shubhanshu-coder** [comment]
pl assign me this issue @rt4914 @bkaur-bkj

**Comment by ArchitJain1201** [comment]
@bkaur-bkj  Can you please assign me this issue?

**Comment by bkaur-bkj** [comment]
> @bkaur-bkj Can you please assign me this issue?

as this issue is currently begin assigned to Shubhanshu you can try picking up other issues

**Comment by shubhanshu-coder** [comment]
can u pl guide me how to start , very eager to contribute.
currently figuring out where the issue code .

**Comment by rt4914** [comment]
> can u pl guide me how to start , very eager to contribute. currently figuring out where the issue code .

@shubhanshu-coder Please checkout our [wiki](https://github.com/oppia/oppia-android/wiki) first. This will help you in setting up the project and once you sign the CLA and fill the survey form we can assign you issues to work on.

**Comment by shubhanshu-coder** [comment]
ok

**Comment by shubhanshu-coder** [comment]
i have filled the CLA and the survey form . now i can start next ?

**Comment by rt4914** [comment]
@shubhanshu-coder You can find CLA here: https://github.com/oppia/oppia-android/wiki/Contributing-to-Oppia-android#onboarding-instructions

**Comment by shubhanshu-coder** [comment]
I have filled it now

**Comment by ArchitJain1201** [comment]
@shubhanshu-coder Are you still working on this issue or Can I take it?

**Comment by shubhanshu-coder** [comment]
> 
@ArchitJain1201 
Yes I am working on it.

**Comment by DeonWaju** [comment]
This issue seems to have been fixed, I tested the develop branch and its been fixed

**Comment by deonwaju** [comment]
This issue seems to have been fixed, I checked the develop branch and its been fixed

**Comment by YesShubham01** [comment]
Yes this issue is fixed. I would like someone from community to close this issue.

**Comment by seanlip** [comment]
@rt4914 is going to verify this and report back. Thanks for the ping.

**Comment by rt4914** [comment]
@YesShubham01 I did check this on latest develop code and it is still not fixed.

**Device Config**:
API 19 Kitkat
Pixel 2
Android 4.4 armeabi-v7a

![Screenshot_20230103_171334](https://user-images.githubusercontent.com/9396084/210350977-0b9bf30d-87a3-4350-ae87-87012ac46bae.png)

**Comment by sumanbmondal** [comment]
@rt4914 I think this is happening because the brown icon is selected for administrator controls. I am able to change it to grey icon. But I'm not able to change the color according to whether the button is selected or not. 


I get the error "This feature requires ASM7" when I try to put conditionals -
![image](https://user-images.githubusercontent.com/94859440/216390236-7ec47a1d-ec5e-477f-af8d-3d7261c89a78.png)

Can you please help me, and if possible assign me the issue?

**Comment by sumanbmondal** [comment]
@seanlip @rt4914 I think this is happening because the brown icon is selected for administrator controls. I am able to change it to grey icon. But I'm not able to change the color according to whether the button is selected or not.

I get the error "This feature requires ASM7" when I try to put conditionals -
![image](https://user-images.githubusercontent.com/94859440/216392098-595518c5-9e54-45c4-b68f-abfe2acde4c0.png)


Can you please help me, and if possible assign me the issue?

**Comment by nawaz-anwar** [comment]
@rt4914 I want to work on this issue. Please assign it to me.

**Comment by seanlip** [comment]
@nawaz-anwar  Please provide an explanation of what your PR will do (with names of files you're changing, what you plan to change in each file, etc.). If it looks good, we can assign you to this issue.

**Comment by sumanbmondal** [comment]
> @seanlip @rt4914 I think this is happening because the brown icon is selected for administrator controls. I am able to change it to grey icon. But I'm not able to change the color according to whether the button is selected or not.
> 
> I get the error "This feature requires ASM7" when I try to put conditionals - ![image](https://user-images.githubusercontent.com/94859440/216392098-595518c5-9e54-45c4-b68f-abfe2acde4c0.png)
> 
> Can you please help me, and if possible assign me the issue?

@seanlip @rt4914 Can you please comment on this?

**Comment by seanlip** [comment]
Per https://github.com/oppia/oppia-android/issues/5012, we are deprecating support for Android KitKat, so this issue is no longer valid.
